CASMPET-5438: GRAFANA- Istio Performance Dashboard - Data not found
Cray-HPE/cray-sysmgmt-health pull request #65
Opened 2022-04-19 07:31 UTC by shreni123

## Summary and Scope

_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_

_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [issue id](issue link)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after `<insert PR URL here>`

## Testing

_List the environments in which these changes were tested._

### Tested on:

  * `<development system>`
  * Local development environment
  * Virtual Shasta

### Test description:

_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?

## Risks and Mitigations

_Are there known issues with these changes? Any other special considerations?_

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [ ] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2022-04-19 08:17 UTC, rambabubolla approved these changes

2022-04-19 17:00 UTC, bo-quan approved these changes

2022-04-19 17:13 UTC, bo-quan requested changes
Chart version 0.21.6 was already used. I don't think a chart change is needed for 1.2 release if it's the same chart as 0.21.12. Only a CSM manifest PR is needed for 1.2 release.

2022-04-20 04:52 UTC, shreni123 commented
> Chart version 0.21.6 was already used. I don't think a chart change is needed for 1.2 release if it's the same chart as 0.21.12. Only a CSM manifest PR is needed for 1.2 release.

We need to bump the chart version otherwise lint test failing because of the same. So bumping the chart version to 0.21.12.

Error image for reference
![image](https://user-images.githubusercontent.com/53111642/164152833-01c26351-663d-48f1-a956-154e2c058b89.png)

2022-04-20 13:30 UTC, bo-quan approved these changes

2022-04-20 13:38 UTC, merged